import { User, UserRole, Project, ProjectStatus, Priority, Task, TaskStatus } from "../types";

export const MOCK_USERS: User[] = [
  { id: "u1", username: "admin", name: "Sarah Management", role: UserRole.MANAGEMENT },
  { id: "u2", username: "lead1", name: "John TeamLead", role: UserRole.TEAM_LEAD },
  { id: "u3", username: "dev1", name: "Alice Developer", role: UserRole.DEVELOPER },
  { id: "u4", username: "dev2", name: "Bob Developer", role: UserRole.DEVELOPER },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Cloud Migration",
    description: "Migrating legacy servers to AWS infrastructure.",
    startDate: "2024-01-01",
    deadline: "2024-06-30",
    priority: Priority.HIGH,
    status: ProjectStatus.ACTIVE,
    assignedLeadId: "u2",
    assignedDeveloperIds: ["u3", "u4"],
    progressPercentage: 45,
  },
  {
    id: "p2",
    name: "Mobile App Redesign",
    description: "Modernizing the UI/UX of our flagship mobile application.",
    startDate: "2024-02-15",
    deadline: "2024-05-15",
    priority: Priority.MEDIUM,
    status: ProjectStatus.PLANNING,
    assignedLeadId: "u2",
    assignedDeveloperIds: ["u3"],
    progressPercentage: 10,
  },
  {
    id: "p3",
    name: "Security Audit",
    description: "Quarterly security assessment and patching.",
    startDate: "2024-03-01",
    deadline: "2024-03-15",
    priority: Priority.URGENT,
    status: ProjectStatus.COMPLETED,
    assignedLeadId: "u2",
    assignedDeveloperIds: ["u4"],
    progressPercentage: 100,
  },
  {
    id: "p4",
    name: "AI Integration",
    description: "Implementing Gemini API for intelligent features.",
    startDate: "2024-04-01",
    deadline: "2024-08-01",
    priority: Priority.HIGH,
    status: ProjectStatus.TESTING,
    assignedLeadId: "u2",
    assignedDeveloperIds: ["u3", "u4"],
    progressPercentage: 75,
  },
  {
    id: "p5",
    name: "Legacy System Decommission",
    description: "Phasing out old hardware and software.",
    startDate: "2024-05-01",
    deadline: "2024-12-01",
    priority: Priority.LOW,
    status: ProjectStatus.MAINTENANCE,
    assignedLeadId: "u2",
    assignedDeveloperIds: ["u4"],
    progressPercentage: 20,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    title: "Database Backup",
    description: "Ensure all databases are backed up before migration.",
    assignedDeveloperId: "u3",
    deadline: "2024-03-20",
    status: TaskStatus.COMPLETED,
    progressPercentage: 100,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-10",
  },
  {
    id: "t2",
    projectId: "p1",
    title: "EC2 Instance Setup",
    description: "Provisioning new EC2 instances in us-east-1.",
    assignedDeveloperId: "u4",
    deadline: "2024-04-15",
    status: TaskStatus.IN_PROGRESS,
    progressPercentage: 60,
    createdAt: "2024-01-15",
    updatedAt: "2024-02-01",
  },
  {
    id: "t3",
    projectId: "p2",
    title: "Figma Prototypes",
    description: "Create high-fidelity prototypes for the new dashboard.",
    assignedDeveloperId: "u3",
    deadline: "2024-03-10",
    status: TaskStatus.PENDING,
    progressPercentage: 0,
    createdAt: "2024-02-20",
    updatedAt: "2024-02-20",
  },
  {
    id: "t4",
    projectId: "p4",
    title: "API Endpoint Testing",
    description: "Verify all Gemini API endpoints are returning correct responses.",
    assignedDeveloperId: "u3",
    deadline: "2024-05-01",
    status: TaskStatus.REVIEW,
    progressPercentage: 90,
    createdAt: "2024-04-05",
    updatedAt: "2024-04-20",
  },
  {
    id: "t5",
    projectId: "p4",
    title: "Frontend Integration",
    description: "Connect the React frontend to the new AI endpoints.",
    assignedDeveloperId: "u4",
    deadline: "2024-06-01",
    status: TaskStatus.CANCELLED,
    progressPercentage: 40,
    createdAt: "2024-04-10",
    updatedAt: "2024-04-25",
  },
];
